#!/usr/bin/env node
/**
 * The quality gate: the single blocking step of the pipeline.
 *
 * Everything upstream (tsc, eslint, vitest, npm audit, jscpd) runs
 * non-blocking and just drops reports on disk. This script reads them, scores
 * them against `quality-baseline.json`, and decides whether the PR may merge.
 *
 *   node scripts/quality-gate.mjs                 # score and gate
 *   node scripts/quality-gate.mjs --update-baseline   # record the current state
 *   node scripts/quality-gate.mjs --json          # verdict JSON on stdout
 *
 * Exit codes: 0 = pass (warnings allowed), 1 = blocked, 2 = could not run.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { collectMetrics, COLLECTOR_METRICS } from './lib/collect-metrics.mjs';
import { STATUS, evaluateMetrics, evaluateShape, snapshotFiles, worstStatus, collectorRegressions } from './lib/evaluate.mjs';
import { COMMENT_MARKER, renderConsole, renderMarkdown } from './lib/report.mjs';
import { HOST_ROOT, REPORTS_DIR, CONFIG_PATH, BASELINE_PATH } from './lib/paths.mjs';

const argv = new Set(process.argv.slice(2));
const UPDATE_BASELINE = argv.has('--update-baseline');
const JSON_ONLY = argv.has('--json');

function log(...args) {
  if (!JSON_ONLY) console.log(...args);
}

function git(...args) {
  try {
    return execFileSync('git', args, { cwd: HOST_ROOT, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function loadJson(path, fallback) {
  if (!existsSync(path)) return fallback;
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    console.error(`Could not parse ${path}: ${error.message}`);
    process.exit(2);
  }
}

const config = loadJson(CONFIG_PATH, null);
if (!config) {
  console.error(`${CONFIG_PATH} is missing.`);
  process.exit(2);
}

const baseline = loadJson(BASELINE_PATH, null);

const { metrics: current, evidence, analysis, unconfigured, failed } = collectMetrics(HOST_ROOT, config);

// --- baseline mode -----------------------------------------------------------

if (UPDATE_BASELINE) {
  // Unconfigured collectors are allowed into a baseline — that is the
  // create-next-app day-one state, and it's what the `unconfigured` WARN
  // path is for. A *failed* collector is different: it means a tool was
  // supposed to run and didn't, so its "current" values are not trustworthy
  // enough to lock in as the ratchet everyone else is measured against.
  if (failed.length > 0) {
    console.error(`Refusing to write a baseline: ${failed.length} collector(s) failed to run:`);
    for (const entry of failed) console.error(`  - ${entry.collector}: ${entry.error}`);
    console.error('Fix the collector(s) and re-run `npm run quality:collect` first.');
    process.exit(2);
  }

  const next = {
    $comment:
      'Generated by `npm run quality:baseline`. Commit this file — it is the ratchet the gate compares every PR against. Only regenerate deliberately, and say why in the PR.',
    generatedAt: new Date().toISOString(),
    commit: git('rev-parse', 'HEAD') || 'unknown',
    branch: git('rev-parse', '--abbrev-ref', 'HEAD') || 'unknown',
    metrics: current,
    totals: analysis.totals,
    files: snapshotFiles(analysis),
    collectors: Object.fromEntries(Object.entries(config.collectors).map(([name, entry]) => [name, entry.adapter])),
  };

  writeFileSync(BASELINE_PATH, `${JSON.stringify(next, null, 2)}\n`);
  log(`Baseline written to ${BASELINE_PATH} at commit ${next.commit.slice(0, 7)}.`);
  log(renderConsole({ metrics: evaluateMetrics(config, current, next.metrics), violations: [] }));
  process.exit(0);
}

// --- gate mode ---------------------------------------------------------------

// Translate collector-level unconfigured/failed status into the metric ids
// each collector owns, so evaluateMetrics can apply the right per-metric
// status instead of the collectors' consumers re-deriving this mapping.
const unconfiguredMetricIds = new Set(unconfigured.flatMap((collector) => COLLECTOR_METRICS[collector] ?? []));
const failedByMetricId = new Map(
  failed.flatMap((entry) => (COLLECTOR_METRICS[entry.collector] ?? []).map((id) => [id, entry.error])),
);

const metricResults = evaluateMetrics(config, current, baseline?.metrics, { unconfiguredMetricIds, failedByMetricId });
const violations = [
  ...evaluateShape(config, analysis, baseline?.files ?? {}),
  ...collectorRegressions(baseline?.collectors, unconfigured),
];

const statuses = [
  ...metricResults.map((entry) => entry.status),
  ...violations.map((entry) => entry.status),
];
const worst = worstStatus(statuses);
const verdict = worst === STATUS.BLOCK ? 'block' : 'pass';

const result = {
  verdict,
  generatedAt: new Date().toISOString(),
  context: {
    commit: git('rev-parse', 'HEAD') || 'unknown',
    branch: git('rev-parse', '--abbrev-ref', 'HEAD') || 'unknown',
    baselineCommit: baseline?.commit ?? null,
    baselineGeneratedAt: baseline?.generatedAt ?? null,
    hasBaseline: baseline !== null,
  },
  counts: {
    blocking:
      metricResults.filter((entry) => entry.status === STATUS.BLOCK).length +
      violations.filter((entry) => entry.status === STATUS.BLOCK).length,
    warning:
      metricResults.filter((entry) => entry.status === STATUS.WARN).length +
      violations.filter((entry) => entry.status === STATUS.WARN).length,
    improved: metricResults.filter((entry) => entry.status === STATUS.IMPROVED).length,
  },
  metrics: metricResults,
  violations,
  evidence,
  totals: analysis.totals,
  unconfigured,
  failed,
};

mkdirSync(REPORTS_DIR, { recursive: true });
writeFileSync(resolve(REPORTS_DIR, 'quality-gate.json'), `${JSON.stringify(result, null, 2)}\n`);

const markdown = renderMarkdown(result);
writeFileSync(resolve(REPORTS_DIR, 'quality-gate.md'), `${markdown}\n`);

if (JSON_ONLY) {
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
} else {
  log(renderConsole(result));
  log('');
  if (!baseline) {
    log('No baseline found. Run `node .loopwright/scripts/quality-gate.mjs --update-baseline` and commit .loopwright/baseline.json.');
  }
  log(
    verdict === 'block'
      ? `QUALITY GATE FAILED — ${result.counts.blocking} blocker(s), ${result.counts.warning} warning(s).`
      : `Quality gate passed — ${result.counts.warning} warning(s), ${result.counts.improved} improvement(s).`,
  );
  log('Reports: .loopwright/reports/quality-gate.json, .loopwright/reports/quality-gate.md');
}

// GitHub step summary, when running in Actions.
if (process.env.GITHUB_STEP_SUMMARY) {
  writeFileSync(process.env.GITHUB_STEP_SUMMARY, `${markdown.replace(COMMENT_MARKER, '')}\n`, { flag: 'a' });
}
if (process.env.GITHUB_OUTPUT) {
  writeFileSync(
    process.env.GITHUB_OUTPUT,
    `verdict=${verdict}\nblocking=${result.counts.blocking}\nwarning=${result.counts.warning}\n`,
    { flag: 'a' },
  );
}

process.exit(verdict === 'block' ? 1 : 0);
