#!/usr/bin/env node
/**
 * The quality gate: the single blocking step of the pipeline.
 *
 * Everything upstream (tsc, eslint, vitest, npm audit, jscpd) runs
 * non-blocking and just drops reports on disk. This script reads them, scores
 * them against `quality-baseline.json`, and decides whether the PR may merge.
 *
 *   node scripts/quality-gate.mjs                 # score and gate
 *   node scripts/quality-gate.mjs --update-baseline   # record the current state
 *   node scripts/quality-gate.mjs --json          # verdict JSON on stdout
 *
 * Exit codes: 0 = pass (warnings allowed), 1 = blocked, 2 = could not run.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { collectMetrics } from './lib/collect-metrics.mjs';
import { STATUS, evaluateMetrics, evaluateShape, snapshotFiles, worstStatus } from './lib/evaluate.mjs';
import { COMMENT_MARKER, renderConsole, renderMarkdown } from './lib/report.mjs';

const ROOT = resolve(import.meta.dirname, '..');
const argv = new Set(process.argv.slice(2));
const UPDATE_BASELINE = argv.has('--update-baseline');
const JSON_ONLY = argv.has('--json');

function log(...args) {
  if (!JSON_ONLY) console.log(...args);
}

function git(...args) {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function loadJson(path, fallback) {
  const target = resolve(ROOT, path);
  if (!existsSync(target)) return fallback;
  try {
    return JSON.parse(readFileSync(target, 'utf8'));
  } catch (error) {
    console.error(`Could not parse ${path}: ${error.message}`);
    process.exit(2);
  }
}

const config = loadJson('quality-gate.config.json', null);
if (!config) {
  console.error('quality-gate.config.json is missing.');
  process.exit(2);
}

const baselinePath = config.baselineFile ?? 'quality-baseline.json';
const baseline = loadJson(baselinePath, null);

const { metrics: current, evidence, analysis, missing } = collectMetrics(ROOT, config);

// --- baseline mode -----------------------------------------------------------

if (UPDATE_BASELINE) {
  if (missing.length > 0) {
    console.error(`Refusing to write a baseline from incomplete data. Missing: ${missing.join(', ')}`);
    console.error('Run `npm run quality:collect` first.');
    process.exit(2);
  }

  const next = {
    $comment:
      'Generated by `npm run quality:baseline`. Commit this file — it is the ratchet the gate compares every PR against. Only regenerate deliberately, and say why in the PR.',
    generatedAt: new Date().toISOString(),
    commit: git('rev-parse', 'HEAD') || 'unknown',
    branch: git('rev-parse', '--abbrev-ref', 'HEAD') || 'unknown',
    metrics: current,
    totals: analysis.totals,
    files: snapshotFiles(analysis),
  };

  writeFileSync(resolve(ROOT, baselinePath), `${JSON.stringify(next, null, 2)}\n`);
  log(`Baseline written to ${baselinePath} at commit ${next.commit.slice(0, 7)}.`);
  log(renderConsole({ metrics: evaluateMetrics(config, current, next.metrics), violations: [] }));
  process.exit(0);
}

// --- gate mode ---------------------------------------------------------------

const metricResults = evaluateMetrics(config, current, baseline?.metrics);
const violations = evaluateShape(config, analysis, baseline?.files ?? {});

const statuses = [
  ...metricResults.map((entry) => entry.status),
  ...violations.map((entry) => entry.status),
];
const worst = worstStatus(statuses);
const verdict = worst === STATUS.BLOCK ? 'block' : 'pass';

const result = {
  verdict,
  generatedAt: new Date().toISOString(),
  context: {
    commit: git('rev-parse', 'HEAD') || 'unknown',
    branch: git('rev-parse', '--abbrev-ref', 'HEAD') || 'unknown',
    baselineCommit: baseline?.commit ?? null,
    baselineGeneratedAt: baseline?.generatedAt ?? null,
    hasBaseline: baseline !== null,
  },
  counts: {
    blocking:
      metricResults.filter((entry) => entry.status === STATUS.BLOCK).length +
      violations.filter((entry) => entry.status === STATUS.BLOCK).length,
    warning:
      metricResults.filter((entry) => entry.status === STATUS.WARN).length +
      violations.filter((entry) => entry.status === STATUS.WARN).length,
    improved: metricResults.filter((entry) => entry.status === STATUS.IMPROVED).length,
  },
  metrics: metricResults,
  violations,
  evidence,
  totals: analysis.totals,
  missing,
};

mkdirSync(resolve(ROOT, 'reports'), { recursive: true });
writeFileSync(resolve(ROOT, 'reports/quality-gate.json'), `${JSON.stringify(result, null, 2)}\n`);

const markdown = renderMarkdown(result);
writeFileSync(resolve(ROOT, 'reports/quality-gate.md'), `${markdown}\n`);

if (JSON_ONLY) {
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
} else {
  log(renderConsole(result));
  log('');
  if (!baseline) {
    log('No baseline found. Run `npm run quality:baseline` and commit quality-baseline.json.');
  }
  log(
    verdict === 'block'
      ? `QUALITY GATE FAILED — ${result.counts.blocking} blocker(s), ${result.counts.warning} warning(s).`
      : `Quality gate passed — ${result.counts.warning} warning(s), ${result.counts.improved} improvement(s).`,
  );
  log('Reports: reports/quality-gate.json, reports/quality-gate.md');
}

// GitHub step summary, when running in Actions.
if (process.env.GITHUB_STEP_SUMMARY) {
  writeFileSync(process.env.GITHUB_STEP_SUMMARY, `${markdown.replace(COMMENT_MARKER, '')}\n`, { flag: 'a' });
}
if (process.env.GITHUB_OUTPUT) {
  writeFileSync(
    process.env.GITHUB_OUTPUT,
    `verdict=${verdict}\nblocking=${result.counts.blocking}\nwarning=${result.counts.warning}\n`,
    { flag: 'a' },
  );
}

process.exit(verdict === 'block' ? 1 : 0);
